[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "zisi"
  timeout = 26

[functions.detail]
  timeout = 26
  memory = 1024

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/api/areas"
  to = "/.netlify/functions/areas"
  status = 200

[[redirects]]
  from = "/api/detail"
  to = "/.netlify/functions/detail"
  status = 200
