[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/api/areas"
  to = "/.netlify/functions/areas"
  status = 200

[[redirects]]
  from = "/api/detail"
  to = "/.netlify/functions/detail"
  status = 200
